
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar";
import "@radix-ui/themes/styles.css";
import { Theme, ThemePanel } from "@radix-ui/themes";
import AuthProvider from "./auth/AuthProvider";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lunch Box",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ml-10 mr-10`}
        style={{background : "#9D6E5A"}}
      >

<AuthProvider> 
       <Theme accentColor="green" grayColor="gray" panelBackground="translucent" radius="full"
       
        >

       
          <NavBar />
          <main >
            {children}
          </main>

          {/* <ThemePanel /> */}
        </Theme>
        </AuthProvider>
      </body>
    </html>
  );
}
